# Generated by Django 3.0.6 on 2020-06-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_records',
            name='date',
            field=models.DateField(),
        ),
    ]
